# ---- GitHub文件源配置 ----
# GitHub用户名(不是昵称), 注意大小写
GitHubUserName: "26ywzm"
# GitHub主题仓库名称
GitHubRepositories: "26-Blog-Code"


# ---- 基础信息配置 ----
# 博主名称, 文章后缀和主页图片上都会使用此名称
User: "26英文字母"
# 用户头像URL
UserAvatar: "/image/sidebar/avatar1.webp"
# 创建时间
WebsiteStartDate: "2024-03-26"
# 个人主页URL
Home: "https://26ywzm.icu"


# ---- 网站配置 ----
# 当前页失去焦点, 页面Title显示文字
WebsiteTitleBlur: "(◍´꒳`◍) Hi ,看过来！看过来！"
# 当前页失去焦点, 页面Title变化, 延时时间, 单位毫秒
WebsiteTitleBlurTimeOut: 500
# 当前页获取焦点, 页面Title显示文字, 显示后延时恢复原Title
WebsiteTitleFocus: "(*´∇｀*) 欢迎回来!"
# 当前页获取焦点, 页面title变化, 延时时间, 单位毫秒
WebsiteTitleFocusTimeOut: 1000
# 网站图标
WebsiteFavicon: 
  light: "/image/website/logo/logo.png"
  dark: "/image/website/logo/logo-dark.png"


# ---- 进度条配置 ----
ProgressBar:
  id: "topProgressBar"
  color: "#77B6FF"
  height: "2px"
  duration: 0.2


# ---- Loading配置 ----
Loading: 
  rebound: 
    tension: 16
    friction: 5
  spinner: 
    id: "spinner"
    radius: 90
    sides: 3
    depth: 4
    colors: 
      background: "#F0F0F0"
      stroke: "#272633"
      base: null
      child: "#272633"
    # When false the spring will reverse normally.
    alwaysForward: true
    # A number from 0.1 to 0.9 || null for full rotation. 
    restAt: 0.5
    renderBase: false


# ---- 页面动效配置 ----
# true || false, 是否渲染主页头图动效
HomeHeaderAnimationRendered: true
# 主页头图动效设置
HomeHeaderAnimation:    
  radius: 15
  density: 0.2
  # 颜色设置, "random" 为随机颜色
  color: "rgba(255, 255, 255, .2)"
  clearOffset: 0.3
# true || false, 是否渲染背景动效
BackAnimationRendered: true
# true || false, IE浏览器是否渲染背景动效（默认为false）
IEBrowserBackAnimationRendered: false
# 背景动效设置
BackAnimation:
  colorSaturation: "60%"
  colorBrightness: "50%"
  colorAlpha: 0.5
  colorCycleSpeed: 5
  verticalPosition: "random"
  horizontalSpeed: 200
  ribbonCount: 3
  strokeSize: 0
  parallaxAmount: -0.2
  animateSections: true


# ---- 主页配置 ----
# 主页图片URL, 推荐尺寸 >= 1920 * 1080, 支持多张, 每次刷新随机设置一张
HomeHeaderImage: 
  - "https://s2.loli.net/2024/06/07/hVBX4Eeck6m3CML.jpg"
  - "https://s2.loli.net/2024/06/07/Meoc1r4IA6nKGHp.jpg"
  - "https://s2.loli.net/2024/06/07/yZSz9F7QCV3smYo.jpg"
  - "https://s2.loli.net/2024/06/07/mQbOHtVKJhM7eBU.jpg"
  - "https://s2.loli.net/2024/06/07/bK5TNXgzduMqjt1.jpg"
  - "https://s2.loli.net/2024/06/07/j15HxGrzs68ahpw.jpg"
  - "https://s2.loli.net/2024/06/07/RiB2VTJWhDz86Mx.jpg"
  - "https://s2.loli.net/2024/06/07/xrEa87tJ6oPZClG.jpg"
  - "https://s2.loli.net/2024/06/07/maJpBrvOgUwY6GT.jpg"
  - "https://s2.loli.net/2024/06/07/bQ6WIuP3CqRsl5c.png"
  - "https://s2.loli.net/2024/06/07/rkjAHnSuDaP54z9.jpg"
  - "https://s2.loli.net/2024/06/07/Z8e6ktHh4VMBJop.jpg"
  - "https://s2.loli.net/2024/06/07/gI6oE4DPec3L1k9.jpg"
  - "https://s2.loli.net/2024/06/07/DmjM4NfPRwsubyt.jpg"
  - "https://s2.loli.net/2024/06/07/m2sdLyN8Rp6ulYb.jpg"
  - "https://s2.loli.net/2024/06/07/vnWEJxKDhVwk4Me.jpg"
  - "https://s2.loli.net/2024/06/07/Tc3B9PtMlO2UxI5.jpg"
  - "https://s2.loli.net/2024/06/07/HNK4LiWyQ7w8tR6.jpg"
  - "https://s2.loli.net/2024/06/07/gQrzxWUINSAeBln.jpg"
  - "https://s2.loli.net/2024/06/07/GRAZtbCNKTIyMDv.jpg"
  - "https://s21.ax1x.com/2024/06/08/pktwX26.jpg"
  - "https://t.mwm.moe/pc"
  - "http://www.98qy.com/sjbz/api.php"
  - "https://www.loliapi.com/acg/"
# 主页头图上的标语, 设置此选项会固定显示文字, 默认为空, 自动获取一句
HomeBannerText: ""


# ---- 文章详情页配置 ----
# 文章详情页图片URL, 支持多张, 每次刷新随机设置一张
ArticleHeaderImage: 
  - "https://s21.ax1x.com/2024/06/08/pktwb5R.png"
  - "https://s21.ax1x.com/2024/06/08/pktwHa9.jpg"
  - "https://s21.ax1x.com/2024/06/08/pkt0Exf.jpg"
  - "https://s21.ax1x.com/2024/06/08/pkt0ARP.jpg"
  - "https://s21.ax1x.com/2024/06/08/pkt0kGt.jpg"
  - "https://s21.ax1x.com/2024/06/08/pkt0PIA.jpg"
  - "https://s2.loli.net/2024/06/08/z5QXZp6JfTKUOnv.jpg"
  - "https://s2.loli.net/2024/06/08/Y9rPvTHckMXj2Oe.jpg"
  - "https://s2.loli.net/2024/06/08/W5ihdeavtQExuqL.jpg"
  - "https://s2.loli.net/2024/06/08/jLf9uKYT3WoPFVS.jpg"
  - "https://s2.loli.net/2024/06/08/YryPwu1FadeTAfj.jpg"
  - "https://s2.loli.net/2024/06/08/b2I1TAodSfnjgmk.jpg"
  - "https://s2.loli.net/2024/06/08/tIqwk5ZCa2DfhNg.png"
  - "https://s2.loli.net/2024/06/08/RHf2C6uzFQxoZ5c.png"
  - "https://s2.loli.net/2024/06/08/6iNyI7PaGnqLMCf.jpg"
  - "https://s2.loli.net/2024/06/08/z45kEOSKsmCAN1t.jpg"
  - "https://s2.loli.net/2024/06/08/HOFD4GVE1W8NtBC.jpg"
# ---- 其他页面配置 ----
# 其他页面头图上的标语, 设置此选项会固定显示文字, 默认为空, 自动获取一句
OtherBannerText: ""


# ---- 错误页面配置 ----
Error:
  icon: "icon-swimming"
  title: "PAGE NOT FOUND"
  content:
    - "很抱歉，您访问的页面不存在！"
    - "可能是输入地址有误或该地址已变更。"
  buttons:
    - 
      icon: "icon-home"
      text: "返回首页"
      href: "/"
      class: ""


# ---- 菜单配置 ----
# 菜单消息
MenuNotice:
  enable: true
  notice: "不畏过往，不惧将来。既然选择远方，就注定风雨兼程。"
  speed: 20

# 菜单列表
MenuList:
  -
    name: "首页"
    icon: "icon-home-fill"
    href: "/"
    type: "index"
    class: ""
    target: "_self"
  - 
    name: "分类"
    icon: "icon-folder-fill"
    href: "/category"
    type: "category"
    class: ""
    target: "_self"
  - 
    name: "标签"
    icon: "icon-discount-fill"
    href: "/tag"
    type: "tag"
    class: ""
    target: "_self"
  -
    name: "归档"
    icon: "icon-calendar-fill"
    href: "/archive"
    type: "archive"
    class: ""
    target: "_self"
  -
    name: "赞赏"
    icon: "icon-heart-fill"
    href: "/donate"
    type: "donate"
    class: ""
    target: "_self"
  -
    name: "关于"
    icon: "icon-about-fill"
    href: "/about"
    type: "about"
    class: ""
    target: "_self"
  -
    name: "推荐"
    icon: "icon-rss"
    href: "/recommend"
    type: "recommend"
    class: ""
    target: "_self"
  -
    name: "搜索"
    icon: "icon-search-menu"
    href: "javascript:;"
    type: ""
    class: "search"
    target: "_self"
  -
    name: "留言板"
    icon: "icon-comments-fill"
    href: "/comment"
    type: "comment"
    class: ""
    target: "_self"
  -
    name: "友情链接"
    icon: "icon-link"
    href: "/friend"
    type: "friend"
    class: ""
    target: "_self"
# 菜单链接
MenuLink:
  -
    name: "知乎"
    icon: "icon-zhihu"
    href: "https://www.zhihu.com/people/26ge-ying-wen-zi-mu-23"
    class: ""
    target: "_blank"
    image: ""
  -
    name: "微博"
    icon: "icon-weibo"
    href: "https://m.weibo.cn/profile/5848326866"
    class: ""
    target: "_blank"
    image: ""
  -
    name: "QQ"
    icon: "icon-qq"
    href: "javascript:;"
    class: "image"
    target: "_self"
    image: "/image/sidebar/qq.jpg"
  -
    name: "微信"
    icon: "icon-wechat"
    href: "javascript:;"
    class: ""
    target: "_self"
    image: ""
  -
    name: "GitHub"
    icon: "icon-github"
    href: "https://github.com/26ywzm"
    class: ""
    target: "_blank"
    image: ""


# ---- 页脚配置 ----
# 页脚样式
FooterStyle: 2
# 页脚标语
BottomText: "<div><span class='face'>ღゝ◡╹)ノ♡</span></div><div>【岂能尽如人意<span><i class='iconfont icon-like-fill'></i></span>但求无愧于心】</div><div>&copy; 2023-2024 WorstOne. All Rights Reserved.</div>"

# ---- 控制台输出 ----
ConsoleList:
  -
    - "你在找什么？"
    - ""
  -
    - "需要我帮忙吗？"
    - ""
  -
    - "这里应该什么都没有哦！"
    - ""


# ---- 字体图标扩展 ----
FontIconExtend: ""


# ---- 赞赏配置 ----
Donate: 
  paypal : ""
  bitcoin: ""
  alipay : "/image/donate/alipay.jpg"
  wechat : "/image/donate/wechat.jpg"


# ---- Algolia配置 ----
Search:
  applicationID: "XAR1P767LX"
  apiKey: "9454b908d51bd3d979deb8c76b840180"
  adminApiKey: "bd5fafbec67db28c38fd5487086cd052"
  chunkSize: 5000
  indexName: "my-hexo-blog"
  fields:
    - content:strip:truncate,0,500
    - excerpt:strip
    - gallery
    - permalink
    - photos
    - slug
    - tags
    - title
  hits:
    page: 10
  labels:
    placeholder: "搜索"
    empty: "未发现与 「${query}」 相关的内容"
    stats: "${hits} 条相关条目，使用了 ${time} 毫秒"

# ---- Comment配置 ----
Comment:
  switch: true
  # 默认类型为 Valine, 可选项 Waline Valine
  type: "Valine" 

# ---- Valine配置 ----
Valine: 
  el: ""
  appId: "jgTEeDQ0m1LDTOV7XWQoVUyI-MdYXbMMI"
  appKey: "aogPg33rWnyZg2I4INZAq9Rj"
  # 必须设置, 国内版本需域名备案
  serverURLs: 
  placeholder: "你是我一生只会遇见一次的惊喜..."
  avatar: "mm"
  meta: "nick,mail,link"
  requiredFields: "nick,mail"
  pageSize: 5
  lang: "zh-cn"
  visitor: true
  enableQQ: true

# ---- Waline配置 ----
Waline:
  el: ".comments-content"
  serverURL: ""
  path: window.location.pathname
  meta: "['nick', 'mail', 'link']"
  requiredMeta: "['nick', 'mail']"
  pageSize: 10
  lang: "zh-cn"
  locale: 
      admin: "博主"
      anonymous: "匿名用户"
      sofa: "快来做第一个评论的人吧 ~"
      placeholder: "你是我一生只会遇见一次的惊喜..."
  dark: "html[color-scheme='dark']"
  search: false
  pageview: true
  comment: true
  copyright: false


# ---- Tocbot配置 ----
Tocbot: 
  switch: true
  tocSelector: ".toc"
  contentSelector: ".article-body"
  headingSelector: "h1, h2, h3, h4, h5"
  headingsOffset: 0
  scrollSmooth: true
  scrollSmoothOffset: -5
  positionFixedSelector: ".toc"
  positionFixedClass: "toc-fixed"


# ---- Require配置 ----
Require:
  baseUrl: "/js/"
  waitSeconds: 100


# ---- Music配置 ----
# 默认为Meting, 值包含APlayer, Meting
Music: 
  type: "Meting"
# APlayer
APlayer:
  container: ".aplayer"
  fixed: true 
  autoplay: false 
  loop: "all"
  order: "random"
  preload: "auto" 
  volume: 0.67 
  mutex: true
  lrcType: 3
  audio:
    -
      name: "Endless Tears"
      artist: "CLIFF EDGE"
      cover: "/music/cover/Endless Tears.jpg"
      url: "/music/song/Endless Tears.mp3"
      lrc: "/music/lrc/Endless Tears.lrc"
# Meting
Meting:
  api: "https://api.i-meto.com/meting/api"
  id: "3778678" 
  lrcshow: false 
  server: "netease" 
  type: "playlist"
  fixed: true 
  autoplay: false 
  loop: "all"
  order: "random"
  preload: "auto" 
  volume: 0.67 
  mutex: true


# ---- Mouse动画配置 ----
Mouse:
  enable: true
  options: 
    size: 6
    sizeF: 24


# ---- Lazy Load ----
LazyLoad:
  default: "/image/website/lazyload.svg"


# ---- Style配置 ----
Style:
  aplayer: "/css/APlayer.css"
  archive: "/css/archive.css"
  base: "/css/base.css"
  clipboard: "/css/clipboard.css"
  code: "/css/code.css"
  donate: "/css/donate.css"
  fancybox: "/css/jquery.fancybox.css"
  footer: "/css/footer.css"
  iconfont: "/iconfont/iconfont.css"
  index: "/css/index.css"
  menuBubble: "/css/menu-bubble.css"
  mouse: "/css/mouse.css"
  page: "/css/page.css"
  post: "/css/post.css"
  search: "/css/search.css"
  tocbot: "/css/tocbot.css"
  valine: "/css/valine.css"
  waline: "/css/waline.css"
  walineCustom: "/css/waline-custom.css"

# ---- Script配置 ----
Script:
  aplayer: "/js/APlayer.min.js"
  config: "/js/require.config.js"
  index: "/js/index.js"
  instantSearch: "/js/instantsearch.min.js"
  iscroll: "/js/iscroll.js"
  jQuery: "/js/jquery-3.4.1.min.js"
  loading: "/js/loading.js"
  meting: "/js/Meting.min.js"
  require: "/js/require.min.js"
  waline: "/js/waline.mjs"
  pageview: "/js/pageview.mjs"
  comment: "/js/comment.mjs"


# ---- Font配置 ----
Font:
  LongCang: "/font/LongCang.css"
  Monda: "/font/Monda.css"
  NotoSansSC: "/font/NotoSansSC.css"
  NotoSerifSC: "/font/NotoSerifSC.css"
  Playball: "/font/Playball.css"
  PTMono: "/font/PTMono.css"
  Roboto: "/font/Roboto.css"
  RobotoSlab: "/font/RobotoSlab.css"
  Rosario: "/font/Rosario.css"
  UbuntuMono: "/font/UbuntuMono.css"


# ---- 文章尾缀配置 ----
Suffix: 
  about: "简单地活着, 肆意又精彩."


# ---- 主题信息配置 ----
Theme: 
  url: "https://github.com/first19326/Hexo-LiveForCode"
  name: "Hexo - Live For Code"

# ---- RSS ----
feed:
  type: atom
  path: atom.xml
  limit: 10

  # 显示每篇文章的访问者数量。
leancloud_visitors:
  enable: true
  app_id: aomBR3PJCGS45nfMxddPuczn-MdYXbMMI 
  app_key: AdxVMX4TqJTOJvweT9kFqT3K